//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment3TryItWebApp.WsdlAnalyzerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsdlAnalyzerService.IServiceWcf")]
    public interface IServiceWcf {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWcf/GetWsdlOperations", ReplyAction="http://tempuri.org/IServiceWcf/GetWsdlOperationsResponse")]
        Assignment3WcfService.Models.WsdlOperation[] GetWsdlOperations(string wsdlUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWcf/GetWsdlOperations", ReplyAction="http://tempuri.org/IServiceWcf/GetWsdlOperationsResponse")]
        System.Threading.Tasks.Task<Assignment3WcfService.Models.WsdlOperation[]> GetWsdlOperationsAsync(string wsdlUrl);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWcfChannel : Assignment3TryItWebApp.WsdlAnalyzerService.IServiceWcf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWcfClient : System.ServiceModel.ClientBase<Assignment3TryItWebApp.WsdlAnalyzerService.IServiceWcf>, Assignment3TryItWebApp.WsdlAnalyzerService.IServiceWcf {
        
        public ServiceWcfClient() {
        }
        
        public ServiceWcfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWcfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWcfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Assignment3WcfService.Models.WsdlOperation[] GetWsdlOperations(string wsdlUrl) {
            return base.Channel.GetWsdlOperations(wsdlUrl);
        }
        
        public System.Threading.Tasks.Task<Assignment3WcfService.Models.WsdlOperation[]> GetWsdlOperationsAsync(string wsdlUrl) {
            return base.Channel.GetWsdlOperationsAsync(wsdlUrl);
        }
    }
}
